---
services:
  app:
    build: .
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - python manage.py migrate && uvicorn --host 0 epitrello.asgi:application
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: docker.io/postgres:18
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
    volumes:
      - db:/var/lib/postgresql/

  redis:
    image: docker.io/redis:7
    command: ["redis-server", "--appendonly", "no"]

volumes:
  db: {}
