---
services:
  app:
    build: .
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - ./manage.py migrate --noinput && uvicorn --host 0 epitrello.asgi:application
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - REDIS_URL=redis://valkey
    depends_on:
      - db
      - valkey

  db:
    image: docker.io/postgres:18
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
    volumes:
      - db:/var/lib/postgresql/

  valkey:
    image: docker.io/valkey/valkey:latest
    tmpfs:
      - /data/

volumes:
  db: {}
