name: CI (SQLite) + Docker image

on:
  push: {}
  pull_request: {}

jobs:
  tests:
    name: Django tests (SQLite)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - run: pip install -r requirements.txt

      - name: Django checks & migrate (SQLite)
        env:
          SECRET_KEY: 1
        run: |
          python manage.py check --deploy --fail-level WARNING || true
          python manage.py migrate --noinput

      - name: Run unit tests
        env:
          SECRET_KEY: 1
        run: python manage.py test

  docker-image:
    name: Build Docker image (on main)
    needs: tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Set lower case owner name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:latest
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO }}:buildcache,mode=max

  deploy:
    needs: docker-image
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download kubectl
        run: |
          mkdir "$HOME/.bin"
          echo "$HOME/.bin" >> "$GITHUB_PATH"
          curl -Lo "$HOME/.bin/kubectl" \
            https://dl.k8s.io/release/v1.35.0/bin/linux/amd64/kubectl

      - name: Cache kubectl
        uses: actions/cache@v5
        with:
          path: ~/.bin/kubectl
          key: kubectl

      - name: setup .kube/config
        run: |
          mkdir "$HOME/.kube"
          echo "${{ secrets.K3S }}" > "$HOME/.kube/config"

      - run: |
          export IMAGEAPP=ghcr.io/${GITHUB_REPOSITORY,,}:$GITHUB_SHA
          export BASE_URL=main.epitrello.epitech.k3s.gmoker.com
          ./manifests/bin/deploy.sh
